import { buildEventImpactSnapshot } from "./events";

function stringValue(value) {
  return value == null ? "" : String(value).trim();
}

function normalizeHex(value) {
  return stringValue(value).replace(/\s+/g, "").toUpperCase();
}

function replaceTokens(template, context) {
  return String(template || "").replace(/\{\{(\w+)\}\}/g, (_, key) => {
    const value = stringValue(context?.[key]);
    return value || `(${key})`;
  });
}

function createSeed(seed) {
  return {
    status: "seeded",
    urgency: 3,
    clock: 0,
    clockMax: 4,
    advancePerTurn: 1,
    advanceOn: "manual",
    impactScope: "none",
    folder: "Random Event Table",
    notes: "",
    ...buildEventImpactSnapshot(),
    ...seed,
  };
}

export const EVENT_TABLES = Object.freeze({
  kingdom: Object.freeze([
    createSeed({
      title: "Collector Overreach",
      trigger: "A royal collector in {{capital}} starts pressing border families for fees the charter does not support.",
      consequenceSummary: "If no one steps in, the anger turns public and the kingdom looks weak or predatory.",
      fallout: "A hearing, protest, or quiet purge follows. The guilty party has backing from someone useful.",
      urgency: 4,
      advanceOn: "turn",
      impactScope: "always",
      unrestImpact: 1,
      renownImpact: -1,
      notes: "Use this when you want a civic leadership scene or a test of the rulers' public legitimacy.",
    }),
    createSeed({
      title: "Granary Rot",
      trigger: "Spoiled grain is discovered in stores meant to support {{capital}} and the nearest claimed farms.",
      consequenceSummary: "If ignored, shortages start early and frightened settlements begin hoarding.",
      fallout: "The problem may be incompetence, sabotage, or a monster nesting near the supply line.",
      advanceOn: "turn",
      impactScope: "always",
      foodImpact: -2,
      unrestImpact: 1,
      notes: "Pair with a food convoy, inspection, or work-site investigation.",
    }),
    createSeed({
      title: "Border Marker Dispute",
      trigger: "Survey stakes near {{hex}} are moved overnight, and both sides claim the better line.",
      consequenceSummary: "If unanswered, the disputed claim hardens into a standing insult and local violence starts.",
      fallout: "The kingdom must decide whether to arbitrate, intimidate, or uncover who moved the markers first.",
      urgency: 4,
      advanceOn: "turn",
      impactScope: "claimed-hex",
      unrestImpact: 1,
      renownImpact: -1,
      notes: "Best in a claimed or contested frontier hex.",
    }),
    createSeed({
      title: "Smuggling Route Opens",
      trigger: "A profitable shadow route starts moving untaxed goods through {{capital}} and nearby roads.",
      consequenceSummary: "If tolerated too long, the smugglers grow bold enough to buy officials and shape policy.",
      fallout: "The route can be crushed, co-opted, or turned into bait for a larger criminal network.",
      clockMax: 6,
      advanceOn: "turn",
      impactScope: "always",
      crimeImpact: 1,
      lumberImpact: -1,
      oreImpact: -1,
      notes: "Useful when you want kingdom choices with no clean answer.",
    }),
    createSeed({
      title: "Harvest Petition",
      trigger: "Farmers beg for labor, tools, or guards before the next harvest closes.",
      consequenceSummary: "If denied, the season's yield shrinks and resentment lingers in every shared meal.",
      fallout: "This can become a road-building, monster-clearing, or political favor scene.",
      advanceOn: "turn",
      impactScope: "always",
      foodImpact: -1,
      unrestImpact: 1,
      notes: "A grounded event for months when the kingdom needs practical problems.",
    }),
    createSeed({
      title: "Festival Demands",
      trigger: "Guild leaders press for a public celebration to prove {{kingdom}} is thriving, not merely surviving.",
      consequenceSummary: "If mishandled, the event turns into mockery, rivalry, or an opportunity for enemies to grandstand.",
      fallout: "Handled well, this can become a stage for allies, recruitment, and renown.",
      urgency: 2,
      advanceOn: "turn",
      impactScope: "always",
      renownImpact: -1,
      luxuriesImpact: -1,
      notes: "A social kingdom event with room for upside if the rulers engage.",
    }),
    createSeed({
      title: "Road Levy Backlash",
      trigger: "A new toll or road labor order near {{hex}} draws louder complaints than expected.",
      consequenceSummary: "If ignored, teamsters divert, merchants complain, and the realm gains a reputation for petty extortion.",
      fallout: "The rulers can revise the order, crack down, or expose whoever twisted the decree for profit.",
      urgency: 3,
      advanceOn: "turn",
      impactScope: "claimed-hex",
      unrestImpact: 1,
      renownImpact: -1,
      notes: "Strong when a road or work site just came online.",
    }),
    createSeed({
      title: "Unexpected Windfall",
      trigger: "A trader or local notable offers a sudden boon if the rulers settle a small but time-sensitive matter first.",
      consequenceSummary: "If no one answers, the offer goes elsewhere and the court looks slow-footed.",
      fallout: "This can be a soft-pressure opportunity event that becomes a loss rather than a disaster.",
      urgency: 2,
      advanceOn: "turn",
      impactScope: "always",
      rpImpact: 2,
      renownImpact: 1,
      notes: "Treat the consequence as the opportunity being lost if the rulers delay.",
    }),
  ]),
  companion: Object.freeze([
    createSeed({
      title: "{{companion}} Demands a Detour",
      trigger: "{{companion}} spots a trail, rumor, or clue they refuse to let pass without comment.",
      consequenceSummary: "If brushed aside, their frustration hardens into distance and they stop volunteering useful truths.",
      fallout: "The detour itself may be small; the real question is what the party is signaling about loyalty.",
      urgency: 3,
      clockMax: 3,
      notes: "Good for influence scenes and travel-time tension.",
    }),
    createSeed({
      title: "Old Oath Calls {{companion}} Back",
      trigger: "Someone from {{companion}}'s past sends a message demanding aid, secrecy, or repayment.",
      consequenceSummary: "If ignored, the old relationship worsens and the cost comes due under worse terms later.",
      fallout: "The request can be genuine, manipulative, or bait meant to pull the companion away.",
      urgency: 4,
      notes: "Use for spotlight and personal stakes.",
    }),
    createSeed({
      title: "Campfire Friction",
      trigger: "A small disagreement involving {{companion}} spills into camp life and starts splitting the group's routine.",
      consequenceSummary: "If nobody addresses it, travel efficiency drops and the companion starts acting on private assumptions.",
      fallout: "This can lead to influence checks, apologies, or a sharpened ideological divide.",
      clockMax: 3,
      notes: "Best during overland stretches and camp scenes.",
    }),
    createSeed({
      title: "{{companion}} Receives Secret Correspondence",
      trigger: "A sealed message reaches {{companion}} through a courier, traveler, or suspicious drop point.",
      consequenceSummary: "If the party leaves it alone too long, the message shapes choices from the shadows.",
      fallout: "The letter may be romantic, political, criminal, or entirely fabricated.",
      urgency: 3,
      notes: "Lets you seed intrigue without forcing betrayal.",
    }),
    createSeed({
      title: "{{companion}} Finds a Personal Clue",
      trigger: "A token, witness, or sign tied to {{companion}}'s unfinished business appears in {{hex}}.",
      consequenceSummary: "If passed over, the clue is lost and the companion remembers who chose convenience over their needs.",
      fallout: "This can become a lead for a personal quest or a revealing conversation at camp.",
      urgency: 3,
      clockMax: 3,
      notes: "Best when the party is already moving fast and must choose what matters.",
    }),
    createSeed({
      title: "{{companion}} Questions the Charter",
      trigger: "{{companion}} openly doubts whether {{kingdom}} is becoming what the party promised it would be.",
      consequenceSummary: "If the concern is dismissed, their support turns conditional and they stop giving the party the benefit of the doubt.",
      fallout: "Use as a values check on recent party or kingdom decisions.",
      urgency: 4,
      notes: "Strong after a hard choice in the kingdom tab.",
    }),
    createSeed({
      title: "Companion Rivalry Surfaces",
      trigger: "{{companion}} clashes with another ally over methods, leadership, or what should happen next.",
      consequenceSummary: "If unresolved, the rivalry becomes the lens through which both companions interpret future scenes.",
      fallout: "This can enrich camp dynamics or split the party's advice network.",
      clockMax: 4,
      notes: "Link this to another companion in notes if you want a paired scene.",
    }),
    createSeed({
      title: "{{companion}} Spots an Unwanted Opportunity",
      trigger: "{{companion}} sees a quick path to power, revenge, or closure that could cost the party elsewhere.",
      consequenceSummary: "If left unspoken, they may act on the chance in a way that forces the party's hand.",
      fallout: "This works well as a temptation event rather than a pure threat.",
      urgency: 4,
      notes: "Good for morally gray scenes and influence pressure.",
    }),
  ]),
  quest: Object.freeze([
    createSeed({
      title: "Rival Claimants Move on {{quest}}",
      trigger: "Another group hears about {{quest}} and starts acting before the party secures the field.",
      consequenceSummary: "If the party delays, the rival group reshapes the objective and forces a harder approach.",
      fallout: "The rivals might be competent, desperate, or politically protected.",
      urgency: 4,
      clockMax: 4,
      notes: "A clean way to accelerate a stalled quest.",
    }),
    createSeed({
      title: "Witness Goes Missing",
      trigger: "A witness or guide tied to {{quest}} vanishes just before the party can question them.",
      consequenceSummary: "If not pursued quickly, the trail cools and someone else controls the narrative.",
      fallout: "The disappearance could be fear, abduction, or a voluntary flight.",
      urgency: 4,
      clockMax: 3,
      notes: "Works for social, mystery, or chase scenes.",
    }),
    createSeed({
      title: "Prize Starts to Rot",
      trigger: "The reward, site, or evidence tied to {{quest}} degrades with every day the party waits.",
      consequenceSummary: "If ignored, the quest can still be completed, but with reduced value and sharper consequences.",
      fallout: "Material decay, political timing, or spiritual corruption can all fill this role.",
      urgency: 3,
      clockMax: 4,
      notes: "Use when you want delay to matter without fully shutting the quest down.",
    }),
    createSeed({
      title: "Local Expectations Shift",
      trigger: "The people most affected by {{quest}} start demanding a different outcome than the party expected.",
      consequenceSummary: "If dismissed, the quest becomes a legitimacy problem instead of a simple objective.",
      fallout: "This is a social complication, not just a logistics problem.",
      urgency: 3,
      notes: "Good for quests with moral weight.",
    }),
    createSeed({
      title: "False Lead Takes Hold",
      trigger: "A convincing but wrong rumor about {{quest}} spreads through camp, court, or the road.",
      consequenceSummary: "If the rumor survives, valuable time is wasted and the real objective gains cover.",
      fallout: "Someone may be lying on purpose or simply repeating what they need to believe.",
      urgency: 3,
      notes: "Useful when the party is drowning in options.",
    }),
    createSeed({
      title: "Urgent Side Oath",
      trigger: "A smaller promise attached to {{quest}} suddenly becomes time-sensitive and emotionally hard to ignore.",
      consequenceSummary: "If dropped, the quest remains possible but someone important stops trusting the party's word.",
      fallout: "This is ideal when you want a side choice that says something about the party.",
      urgency: 3,
      notes: "Let the side oath reshape the route rather than replace the quest.",
    }),
    createSeed({
      title: "Evidence Lands in Enemy Hands",
      trigger: "A clue tied to {{quest}} is stolen, bought, or copied by someone who now has leverage.",
      consequenceSummary: "If the party does nothing, the next scene begins with their enemy better informed than they are.",
      fallout: "The stolen piece can be a map, witness statement, relic, or coded ledger.",
      urgency: 4,
      clockMax: 3,
      notes: "A strong fit for intrigue and chase play.",
    }),
    createSeed({
      title: "Quest Patron Loses Patience",
      trigger: "The patron behind {{quest}} wants proof of progress now, not at the end of the trail.",
      consequenceSummary: "If no proof arrives, support thins out and the patron starts hedging with other agents.",
      fallout: "The party may need a visible win, not just a correct plan.",
      urgency: 3,
      clockMax: 4,
      notes: "Excellent for keeping a patron in play without constant exposition.",
    }),
  ]),
  travel: Object.freeze([
    createSeed({
      title: "Cold Rain and Black Roads",
      trigger: "Heavy weather turns the route near {{hex}} into slow misery and strips away confidence.",
      consequenceSummary: "If the party pushes through without adapting, fatigue and mistakes feed whatever is already stalking them.",
      fallout: "Camp quality, scouting, and supplies all matter more than usual.",
      urgency: 3,
      clockMax: 3,
      notes: "Grounded in Kingmaker's weather pressure and overland pacing.",
    }),
    createSeed({
      title: "Washed Ford",
      trigger: "The crossing ahead is no longer routine, and every safe option costs time or exposes the party elsewhere.",
      consequenceSummary: "If the delay is mishandled, whatever the party is racing against gains a visible lead.",
      fallout: "A ford, bridge, or ferry scene can open new rumors and NPC contact.",
      urgency: 3,
      clockMax: 3,
      notes: "A classic travel delay that still creates decisions.",
    }),
    createSeed({
      title: "Camp Predator Sign",
      trigger: "Fresh tracks circle the party's chosen campsite, and whatever made them is testing the perimeter.",
      consequenceSummary: "If the warning is ignored, the night's rest turns into a messy interruption or lost supplies.",
      fallout: "You can play this as a beast, fey prank, or deliberate scout.",
      urgency: 4,
      clockMax: 2,
      notes: "Strong for overnight pressure.",
    }),
    createSeed({
      title: "Guide Wants a New Price",
      trigger: "A local guide, hunter, or ferryman decides the current route is worth more than agreed.",
      consequenceSummary: "If the party refuses without a backup, they lose time and goodwill at once.",
      fallout: "The demand might hide fear, greed, or knowledge of a threat ahead.",
      urgency: 3,
      notes: "Good for roleplay while still affecting pace.",
    }),
    createSeed({
      title: "Fog-Lost Trail",
      trigger: "Mist and bad landmarks near {{hex}} make the obvious route unreliable and the wrong turn tempting.",
      consequenceSummary: "If the party guesses wrong, they arrive late, exposed, or exactly where something wants them.",
      fallout: "Excellent for fey influence, bad maps, or false confidence.",
      urgency: 3,
      clockMax: 3,
      notes: "Use when hex travel should feel like a choice, not a tax.",
    }),
    createSeed({
      title: "Supply Break",
      trigger: "A critical travel item breaks or goes missing right when the road becomes less forgiving.",
      consequenceSummary: "If not replaced or worked around, the party pays for it at the next dangerous moment.",
      fallout: "This can be a wagon axle, rope, feed sack, medicine kit, or bedroll cache.",
      urgency: 2,
      clockMax: 3,
      notes: "Small on paper, meaningful in play.",
    }),
    createSeed({
      title: "Hunters with the Wrong Map",
      trigger: "Locals on the move swear they know a shortcut through {{hex}}, but their certainty does not match the land.",
      consequenceSummary: "If trusted blindly, the party stumbles into a worse route or an occupied site.",
      fallout: "The hunters may be naive, lying, or trying to avoid their own danger.",
      urgency: 2,
      notes: "A soft social travel complication.",
    }),
    createSeed({
      title: "Camp Rumor Arrives Before Sunset",
      trigger: "Travelers bring a rumor that changes what the party thinks tomorrow's route means.",
      consequenceSummary: "If left untested, the rumor distorts priorities and drags attention off the real pressure.",
      fallout: "Even a false rumor can reveal what nearby people are afraid of.",
      urgency: 2,
      notes: "Great for moving attention toward a new hex or event front.",
    }),
  ]),
  threat: Object.freeze([
    createSeed({
      title: "Bandit Collection Run",
      trigger: "Bandits or rough claimants start treating {{hex}} as if tribute is already owed to them.",
      consequenceSummary: "If the party lets the collection happen, fear becomes policy and locals stop believing in protection.",
      fallout: "The collectors may be desperate, organized, or testing the party before a larger move.",
      urgency: 5,
      clockMax: 4,
      advanceOn: "turn",
      impactScope: "claimed-hex",
      unrestImpact: 1,
      notes: "A direct Kingmaker frontier pressure event.",
    }),
    createSeed({
      title: "Monster Migration",
      trigger: "A dangerous beast or pack starts crossing through {{hex}} instead of staying in its old ground.",
      consequenceSummary: "If not redirected or hunted, the migration redraws which roads and camps are safe.",
      fallout: "Tracks, refugees, and half-devoured game all point toward the move.",
      urgency: 4,
      clockMax: 4,
      impactScope: "claimed-hex",
      notes: "Useful for making map choices feel alive.",
    }),
    createSeed({
      title: "Troll Scout Signs",
      trigger: "Scouting evidence suggests something larger is measuring the frontier rather than merely passing through.",
      consequenceSummary: "If ignored, the next contact happens on the enemy's terms and at a worse location.",
      fallout: "This works as advance warning before a raid or lair push.",
      urgency: 5,
      clockMax: 3,
      advanceOn: "turn",
      impactScope: "claimed-hex",
      unrestImpact: 1,
      notes: "Use for visible escalation.",
    }),
    createSeed({
      title: "Fey Boundary Warning",
      trigger: "A fey sign, prank, or messenger makes it clear that someone thinks the party crossed a line.",
      consequenceSummary: "If treated like a joke, the frontier itself starts answering in stranger and sharper ways.",
      fallout: "A social encounter, a curse, or a warped route can all follow.",
      urgency: 3,
      clockMax: 4,
      notes: "A non-bandit threat that still feels Kingmaker.",
    }),
    createSeed({
      title: "Charter Papers Stolen",
      trigger: "Something tied to the party's legal authority goes missing and reappears where it can do damage.",
      consequenceSummary: "If not recovered, enemies gain leverage over every argument about who belongs here.",
      fallout: "This may start as theft but should reveal intent fast.",
      urgency: 4,
      clockMax: 3,
      notes: "Turns abstract authority into a scene problem.",
    }),
    createSeed({
      title: "Camp Sabotage",
      trigger: "Tools, traps, or stores are quietly tampered with near {{hex}}.",
      consequenceSummary: "If the sabotage is not answered, the next crisis arrives with the party half-prepared.",
      fallout: "Perfect for testing watch choices and camp procedure.",
      urgency: 4,
      clockMax: 3,
      notes: "Strong overnight threat pressure.",
    }),
    createSeed({
      title: "Frontier Claim Jumper",
      trigger: "A violent opportunist starts acting as though {{hex}} already belongs to them.",
      consequenceSummary: "If the party does not contest the claim, locals start paying the wrong banner.",
      fallout: "The claim jumper could be a villain, a desperate settler, or a proxy for someone worse.",
      urgency: 4,
      clockMax: 4,
      advanceOn: "turn",
      impactScope: "claimed-hex",
      renownImpact: -1,
      unrestImpact: 1,
      notes: "Excellent in newly claimed territory.",
    }),
    createSeed({
      title: "Hidden Cell Awakens",
      trigger: "A small but dangerous group decides conditions are favorable enough to act openly.",
      consequenceSummary: "If allowed room, the cell turns one isolated incident into a pattern the party must chase.",
      fallout: "The cell can be political, monstrous, or cultic depending on your chapter needs.",
      urgency: 4,
      clockMax: 4,
      advanceOn: "turn",
      impactScope: "always",
      crimeImpact: 1,
      notes: "Use when you want a multi-scene threat arc.",
    }),
  ]),
  story: Object.freeze([
    createSeed({
      title: "Messenger from Brevoy",
      trigger: "A rider arrives carrying news, pressure, or expectation from beyond the frontier.",
      consequenceSummary: "If unanswered, outside powers start assuming the party can be managed rather than consulted.",
      fallout: "The message can open diplomacy, suspicion, or a resource request.",
      urgency: 3,
      notes: "A clean way to reconnect the frontier to larger politics.",
    }),
    createSeed({
      title: "Old Border Monument Found",
      trigger: "Something in {{hex}} reveals that the land remembers older rulers, promises, or bloodshed.",
      consequenceSummary: "If no one investigates, another faction claims the meaning first.",
      fallout: "The monument can point to treasure, history, or a sleeping feud.",
      urgency: 2,
      notes: "Good for lore delivery that still changes choices.",
    }),
    createSeed({
      title: "Merchant with Better Information",
      trigger: "A passing merchant knows something the party needs, but only if they make time to listen and bargain.",
      consequenceSummary: "If ignored, the clue leaves with the caravan and reappears somewhere less convenient.",
      fallout: "The merchant can be a rumor broker, neutral witness, or future recurring face.",
      urgency: 2,
      notes: "A low-threat story beat that can seed multiple tabs.",
    }),
    createSeed({
      title: "Dream Omen",
      trigger: "One of the party or companions receives a dream that clearly points toward unfinished business.",
      consequenceSummary: "If dismissed, the omen returns later in a harsher or more public form.",
      fallout: "Use this when you want mythic color without forcing prophecy.",
      urgency: 2,
      notes: "Excellent as connective tissue between exploration and character arcs.",
    }),
    createSeed({
      title: "Unexpected Ally at Camp",
      trigger: "A traveler, scout, or local notable arrives with something that feels too useful to be simple.",
      consequenceSummary: "If treated carelessly, the ally slips away or reveals a hidden agenda on someone else's timing.",
      fallout: "They may be honest, compromised, or watching how the party handles strangers.",
      urgency: 2,
      notes: "Lets you introduce NPCs with leverage.",
    }),
    createSeed({
      title: "Rumor from the Greenbelt",
      trigger: "Stories out of {{hex}} agree on one thing: something is changing faster than the maps do.",
      consequenceSummary: "If left untested, the rumor shapes route choices and spawns secondary fear.",
      fallout: "Use this as a pivot toward exploration, threat, or story content.",
      urgency: 2,
      notes: "A sandbox steering tool more than a danger in itself.",
    }),
    createSeed({
      title: "Recovered Map Fragment",
      trigger: "A fragment of an older map turns up with enough truth in it to tempt bad decisions.",
      consequenceSummary: "If no one validates it, the fragment will still influence someone else's move.",
      fallout: "Combine with exploration, treasure, or old claims.",
      urgency: 3,
      notes: "A quiet story event that can become a quest seed.",
    }),
    createSeed({
      title: "Public Question of Authority",
      trigger: "Someone asks, in front of the wrong audience, who truly gave the party the right to decide this.",
      consequenceSummary: "If the moment passes unanswered, doubt spreads faster than any formal decree can clean up.",
      fallout: "This can be a speech, duel of reputations, or a chance to show visible justice.",
      urgency: 3,
      notes: "Excellent when the campaign needs a legitimacy check rather than a fight.",
    }),
  ]),
});

function buildContext(campaign, options = {}) {
  return {
    category: stringValue(options.category) || "story",
    hex: normalizeHex(options.hex) || "an exposed hex",
    quest: stringValue(options.linkedQuest) || "the current objective",
    companion: stringValue(options.linkedCompanion) || "a companion",
    capital: stringValue(campaign?.kingdom?.capital) || "the capital",
    kingdom: stringValue(campaign?.kingdom?.name) || "the kingdom",
  };
}

export function getEventTable(category) {
  return EVENT_TABLES[stringValue(category).toLowerCase()] || EVENT_TABLES.story;
}

export function resolveEventTableEntry(entry, campaign, options = {}) {
  const context = buildContext(campaign, options);
  return {
    ...entry,
    hex: normalizeHex(options.hex),
    linkedQuest: stringValue(options.linkedQuest),
    linkedCompanion: stringValue(options.linkedCompanion),
    title: replaceTokens(entry?.title, context),
    trigger: replaceTokens(entry?.trigger, context),
    consequenceSummary: replaceTokens(entry?.consequenceSummary, context),
    fallout: replaceTokens(entry?.fallout, context),
    notes: replaceTokens(entry?.notes, context),
  };
}

export function rollEventTable(category, campaign, options = {}) {
  const table = getEventTable(category);
  if (!table.length) {
    return null;
  }
  const roll = Math.floor(Math.random() * table.length);
  const entry = table[roll];
  return {
    category: stringValue(category) || "story",
    size: table.length,
    roll: roll + 1,
    entry,
    preview: resolveEventTableEntry(entry, campaign, options),
  };
}

export function buildGeneratedEventDraft(result, campaign, options = {}) {
  const preview = result?.preview || resolveEventTableEntry(result?.entry || {}, campaign, options);
  return {
    id: "",
    title: preview.title || "New Event",
    folder: preview.folder || "Random Event Table",
    category: preview.category || stringValue(options.category) || "story",
    status: preview.status || "seeded",
    urgency: Number(preview.urgency) || 3,
    hex: normalizeHex(preview.hex || options.hex),
    linkedQuest: stringValue(preview.linkedQuest || options.linkedQuest),
    linkedCompanion: stringValue(preview.linkedCompanion || options.linkedCompanion),
    clock: Number(preview.clock) || 0,
    clockMax: Math.max(1, Number(preview.clockMax) || 4),
    advancePerTurn: Math.max(0, Number(preview.advancePerTurn) || 0),
    advanceOn: stringValue(preview.advanceOn) || "manual",
    impactScope: stringValue(preview.impactScope) || "none",
    trigger: stringValue(preview.trigger),
    fallout: stringValue(preview.fallout),
    consequenceSummary: stringValue(preview.consequenceSummary),
    notes: stringValue(preview.notes),
    ...buildEventImpactSnapshot(preview),
  };
}
