export const KINGMAKER_CONTENT_LIBRARY_VERSION = "kingmaker-canon-v4-source-aligned";

function npc(id, input = {}) {
  return {
    id: `km-npc-${id}`,
    status: "offstage",
    disposition: "indifferent",
    importance: "supporting",
    creatureLevel: 0,
    hex: "",
    linkedQuest: "",
    linkedEvent: "",
    kingdomRole: "",
    kingdomNotes: "",
    folder: "Kingmaker / Cast",
    ...input,
  };
}

function quest(id, input = {}) {
  return {
    id: `km-quest-${id}`,
    status: "watch",
    priority: "Later",
    folder: "Kingmaker / Quest Library",
    hex: "",
    linkedCompanion: "",
    linkedEvent: "",
    blockers: "",
    reward: "",
    ...input,
  };
}

function site(id, input = {}) {
  return {
    id: `km-location-${id}`,
    type: "landmark",
    status: "rumor",
    hex: "",
    controllingFaction: "",
    linkedQuest: "",
    linkedEvent: "",
    linkedNpc: "",
    folder: "Kingmaker / Location Library",
    ...input,
  };
}

export const KINGMAKER_NPC_LIBRARY = Object.freeze([
  npc("jamandi-aldori", {
    name: "Jamandi Aldori",
    role: "Charter patron",
    faction: "Restov Swordlords",
    status: "ally",
    disposition: "helpful",
    importance: "pillar",
    creatureLevel: 10,
    location: "Restov",
    hex: "A1",
    agenda: "Turn the charter into visible proof that Restov can project order into the Stolen Lands.",
    leverage: "Legal authority, swordlord prestige, and political access.",
    pressure: "Needs evidence before rivals call the charter naive.",
    firstImpression: "Composed, dangerous, and judging competence from the first conversation.",
    rumor: "Restov is already guessing which charter parties will fail.",
    secret: "She is evaluating future rulers, not only problem-solvers.",
    nextScene: "Demand proof, offer a hard favor, or ask why the frontier has not improved yet.",
    kingdomRole: "Patron and legitimacy benchmark",
    kingdomNotes: "Her confidence gives the young kingdom political cover.",
    notes: "Opening patron and recurring pressure source.",
    folder: "Chapter 1 / Restov",
  }),
  npc("oleg-leveton", {
    name: "Oleg Leveton",
    role: "Trading post owner",
    faction: "Oleg's Trading Post",
    status: "ally",
    disposition: "friendly",
    importance: "major",
    creatureLevel: 1,
    location: "Oleg's Trading Post",
    hex: "D4",
    agenda: "Keep the post from becoming a permanent bandit feeding trough.",
    leverage: "Supplies, road knowledge, blunt local rumors.",
    pressure: "Angry enough to act before the party is fully ready.",
    firstImpression: "Tired, wary, and only relieved after proof.",
    rumor: "He knows which travelers changed routes when bandit pressure rose.",
    secret: "Fear has made him more willing to gamble than he admits.",
    nextScene: "Put repairs, supplies, tribute pressure, or a practical warning in front of the party.",
    linkedQuest: "Secure Oleg's Trading Post",
    linkedEvent: "First Bandit Collection Run",
    kingdomRole: "Frontier logistics anchor",
    kingdomNotes: "A stable Oleg's becomes the first believable supply hub.",
    folder: "Chapter 3 / Stolen Lands",
  }),
  npc("svetlana-leveton", {
    name: "Svetlana Leveton",
    role: "Trading post co-owner",
    faction: "Oleg's Trading Post",
    status: "ally",
    disposition: "friendly",
    importance: "supporting",
    creatureLevel: 1,
    location: "Oleg's Trading Post",
    hex: "D4",
    agenda: "Keep people fed, calm, and willing to believe the post can survive.",
    leverage: "Hospitality, emotional intelligence, and local trust.",
    pressure: "Small losses are adding up into evacuation thinking.",
    firstImpression: "Warm, watchful, and stronger than she first appears.",
    rumor: "She hears fear early because people lower their guard around her.",
    secret: "She has already thought through what must be abandoned if the post falls.",
    nextScene: "Offer a human-scale favor, morale read, or quiet account of bandit damage.",
    linkedQuest: "Secure Oleg's Trading Post",
    kingdomRole: "Community pulse",
    kingdomNotes: "Her trust measures whether the frontier feels protected.",
    folder: "Chapter 3 / Stolen Lands",
  }),
  npc("kesten-garess", {
    name: "Kesten Garess",
    role: "Swordlord agent",
    faction: "Restov Swordlords",
    status: "watch",
    disposition: "indifferent",
    importance: "major",
    creatureLevel: 4,
    location: "Oleg's Trading Post",
    hex: "D4",
    agenda: "Restore order through disciplined force before the frontier embarrasses Restov.",
    leverage: "Soldiers, official backing, and tactical credibility.",
    pressure: "Reads hesitation as the first step toward losing control.",
    firstImpression: "Capable, impatient, and easier to respect than to like.",
    rumor: "Some claim he would rather command the response than advise it.",
    secret: "His pride and concern are tangled together.",
    nextScene: "Challenge a soft plan or demand proof that a delay is not cowardice.",
    linkedQuest: "Secure Oleg's Trading Post",
    linkedEvent: "Jamandi Wants Results",
    kingdomRole: "Military hardliner",
    kingdomNotes: "Tests authority, security, and command before the kingdom has institutions.",
    folder: "Chapter 3 / Stolen Lands",
  }),
  npc("jhod-kavken", {
    name: "Jhod Kavken",
    role: "Wandering priest",
    faction: "Erastil Faithful",
    status: "ally",
    disposition: "friendly",
    importance: "major",
    location: "Oleg's Trading Post",
    agenda: "Restore sacred order in the wilderness.",
    leverage: "Faith, healing, old stories, and a moral argument for restoration.",
    pressure: "Holy places left corrupted make settlers read the land as cursed.",
    firstImpression: "Earnest, tired, and hungry for proof that hope is not foolish.",
    rumor: "He searches for an old shrine tied to the Greenbelt's better past.",
    secret: "He needs the party to validate his faith as much as he needs help.",
    nextScene: "Ask the party to follow a sign, bless a recovered site, or choose mercy.",
    linkedQuest: "Restore the Temple of the Elk",
    kingdomRole: "Early spiritual legitimacy",
    kingdomNotes: "Can help settlers see the kingdom as protector, not claimant.",
    folder: "Chapter 2 / Into the Wild",
  }),
  npc("bokken", {
    name: "Bokken",
    role: "Potion maker and hermit",
    faction: "Greenbelt Locals",
    status: "neutral",
    importance: "supporting",
    location: "Bokken's Hut",
    agenda: "Get rare ingredients while keeping everyone at a comfortable distance.",
    leverage: "Alchemy, odd rumors, and a willingness to trade help for dangerous errands.",
    pressure: "Needs materials from places he cannot safely reach.",
    firstImpression: "Erratic, useful, and hard to pin down.",
    rumor: "He knows which plants and beasts mark nearby danger.",
    secret: "His isolation makes him more observant than expected.",
    nextScene: "Trade a practical reward for a strange reagent or trail clue.",
    linkedQuest: "Help Bokken's Reagent Work",
    kingdomRole: "Rural craft contact",
    folder: "Chapter 2 / Into the Wild",
  }),
  npc("happs-bydon", {
    name: "Happs Bydon",
    role: "Bandit lieutenant",
    faction: "Stag Lord's Bandits",
    status: "hostile",
    disposition: "hostile",
    location: "Oleg's road",
    agenda: "Keep tribute flowing and make resistance expensive.",
    leverage: "Fear, riders, and knowledge of who has paid before.",
    pressure: "If humiliated, the bandits need a fast answer or lose grip.",
    firstImpression: "Smug violence wrapped around survival instinct.",
    rumor: "He brags enough that survivors can repeat his patterns.",
    secret: "He is more replaceable to his superiors than he realizes.",
    nextScene: "Use as the face of the first tribute run.",
    linkedQuest: "Secure Oleg's Trading Post",
    linkedEvent: "First Bandit Collection Run",
    folder: "Chapter 3 / Bandits",
  }),
  npc("kressle", {
    name: "Kressle",
    role: "Bandit camp leader",
    faction: "Stag Lord's Bandits",
    status: "hostile",
    disposition: "hostile",
    importance: "major",
    location: "Thorn River Camp",
    agenda: "Keep her camp feared, profitable, and independent enough to matter.",
    leverage: "Ambush ground, bandit loyalty, and knowledge of the Stag Lord's operation.",
    pressure: "A failed collection run makes her look weak.",
    firstImpression: "Sharp, violent, and used to being underestimated at someone's cost.",
    rumor: "Her camp is where scared tribute turns into organized theft.",
    secret: "She knows enough to be a dangerous prisoner or informant.",
    nextScene: "Force a choice between justice, interrogation, and retaliation risk.",
    linkedQuest: "Break the Thorn River Bandits",
    folder: "Chapter 3 / Bandits",
  }),
  npc("stag-lord", {
    name: "The Stag Lord",
    role: "Bandit warlord",
    faction: "Stag Lord's Bandits",
    status: "hostile",
    disposition: "hostile",
    importance: "pillar",
    location: "Stag Lord's Fort",
    agenda: "Rule through fear, tribute, and the myth that resistance only feeds his legend.",
    leverage: "A fortified base, lieutenants, terror, and unanswered raids.",
    pressure: "Every lost camp chips away at his aura.",
    firstImpression: "A rumor before he is a person: feared, antlered, and larger than facts.",
    rumor: "Travelers speak his name as if saying it too loudly might draw attention.",
    secret: "His command structure has cracks the party can widen.",
    nextScene: "Escalate his presence through orders, signs, prisoners, or a lieutenant's panic.",
    linkedQuest: "Confront the Stag Lord",
    kingdomRole: "First legitimacy gate",
    kingdomNotes: "Defeating him proves the charter can protect territory.",
    folder: "Chapter 3 / Bandits",
  }),
  npc("akiros-ismort", {
    name: "Akiros Ismort",
    role: "Conflicted bandit officer",
    faction: "Stag Lord's Bandits",
    status: "watch",
    importance: "major",
    location: "Stag Lord's Fort",
    agenda: "Survive his bad choices while looking for one better choice.",
    leverage: "Inside knowledge, martial skill, and doubts about the Stag Lord.",
    pressure: "The party's conduct can push him toward redemption, betrayal, or collapse.",
    firstImpression: "Dangerous, guarded, and carrying more than mere loyalty.",
    rumor: "Not everyone in the fort follows the Stag Lord for the same reason.",
    secret: "His conscience is a pressure point if noticed in time.",
    nextScene: "Give him one chance to see the party act with discipline.",
    linkedQuest: "Confront the Stag Lord",
    kingdomRole: "Possible redemption case",
    folder: "Chapter 3 / Bandits",
  }),
  npc("nugrah", {
    name: "Nugrah",
    role: "Stag Lord's father",
    faction: "Stag Lord's Bandits",
    status: "hostile",
    disposition: "hostile",
    location: "Stag Lord's Fort",
    agenda: "Feed old hatred and keep the fort spiritually poisoned.",
    leverage: "Cruel magic, family trauma, and fear within the fort.",
    pressure: "Explains why some wounds around the Stag Lord do not close cleanly.",
    firstImpression: "A rotten root under a rotten tree.",
    rumor: "The Stag Lord's cruelty did not start with him.",
    nextScene: "Reveal personal damage behind the public threat without excusing crimes.",
    linkedQuest: "Confront the Stag Lord",
    folder: "Chapter 3 / Bandits",
  }),
  npc("dovan-from-nisroch", {
    name: "Dovan from Nisroch",
    role: "Bandit sadist",
    faction: "Stag Lord's Bandits",
    status: "hostile",
    disposition: "hostile",
    location: "Stag Lord's Fort",
    agenda: "Profit from chaos and enjoy having cover for cruelty.",
    leverage: "Fear, manipulation, and willingness to escalate beyond practical theft.",
    pressure: "More dangerous when the fort starts losing discipline.",
    firstImpression: "Silken menace with a knife behind every smile.",
    rumor: "Even other bandits dislike what he does when nobody stops him.",
    secret: "He is loyal to opportunity, not the Stag Lord.",
    nextScene: "Make him the argument for why some threats cannot be negotiated away.",
    linkedQuest: "Confront the Stag Lord",
    folder: "Chapter 3 / Bandits",
  }),
  npc("chief-sootscale", {
    name: "Chief Sootscale",
    role: "Kobold chief",
    faction: "Sootscale Kobolds",
    status: "watch",
    importance: "major",
    location: "Sootscale Caverns",
    agenda: "Keep his tribe alive without losing authority to Tartuk's fear and magic.",
    leverage: "Tribal loyalty, local tunnel knowledge, and a claim to Sootscale survival.",
    pressure: "The mite-kobold conflict and Tartuk's influence strain his rule.",
    firstImpression: "Proud, cornered, and looking for strength he can respect.",
    rumor: "The kobolds are not united in why they fight.",
    secret: "His authority can be restored if the right problem is solved.",
    nextScene: "Turn a dungeon crawl into a choice about alliance and future neighbors.",
    linkedQuest: "Stabilize Sootscale Caverns",
    kingdomRole: "Potential nonhuman neighbor",
    folder: "Chapter 2 / Old Sycamore",
  }),
  npc("tartuk", {
    name: "Tartuk",
    role: "Kobold shaman",
    faction: "Sootscale Kobolds",
    status: "hostile",
    disposition: "hostile",
    importance: "major",
    location: "Sootscale Caverns",
    agenda: "Use fear, prophecy, and confusion to keep the kobolds under his influence.",
    leverage: "Magic, superstition, and control of the crisis narrative.",
    pressure: "Any proof the tribe can survive without him threatens his position.",
    firstImpression: "Grandiose, theatrical, and more dangerous than a simple trickster.",
    rumor: "The purple shaman's words turned fear into doctrine.",
    secret: "He needs the conflict to continue because peace exposes him.",
    nextScene: "Separate genuine kobold interests from manipulation.",
    linkedQuest: "Stabilize Sootscale Caverns",
    folder: "Chapter 2 / Old Sycamore",
  }),
  npc("perlivash", {
    name: "Perlivash",
    role: "Faerie dragon prankster",
    faction: "Narlmarches Fey",
    status: "neutral",
    disposition: "friendly",
    location: "Narlmarches",
    agenda: "Test whether the charter party can laugh, listen, and avoid acting like conquerors.",
    leverage: "Fey mobility, misdirection, and access to hidden local patterns.",
    pressure: "Cruel or humorless choices make future fey contact colder.",
    firstImpression: "Playful, evasive, and watching for whether the party ruins the joke.",
    rumor: "Helpful laughter in the woods may still be a test.",
    nextScene: "Reward kindness with a clue or punish arrogance with harmless trouble.",
    linkedQuest: "Earn the Fey's Trust",
    kingdomRole: "Fey contact",
    folder: "Chapter 2 / Fey",
  }),
  npc("old-beldame", {
    name: "Old Beldame",
    role: "Reclusive local spellcaster",
    faction: "Greenbelt Locals",
    status: "watch",
    disposition: "unfriendly",
    importance: "major",
    location: "Old Beldame's Hut",
    agenda: "Keep fools, politics, and accusations far from her door.",
    leverage: "Local magical knowledge, independence, and a reputation people misunderstand.",
    pressure: "Suspicion around her can become a community problem.",
    firstImpression: "Sharp-tongued, isolated, and unwilling to perform innocence for strangers.",
    rumor: "The frontier often calls a woman dangerous before asking what she knows.",
    secret: "She can become a valuable contact if treated as a person, not a rumor.",
    nextScene: "Let the party earn trust through restraint, respect, or a useful favor.",
    kingdomRole: "Independent local power",
    folder: "Chapter 2 / Greenbelt",
  }),
  npc("hargulka", {
    name: "Hargulka",
    role: "Troll warlord",
    faction: "Troll Kingdom",
    status: "hostile",
    disposition: "hostile",
    importance: "pillar",
    location: "Hargulka's Stronghold",
    agenda: "Build a monster kingdom before the charter kingdom secures its borders.",
    leverage: "Troll strength, organized raids, and fear of what the wilderness can become.",
    pressure: "Every delayed response makes his forces look more like a rival state.",
    firstImpression: "Not a wandering brute, but a ruler of violence with territory in mind.",
    rumor: "The trolls are becoming too organized to treat as random monsters.",
    nextScene: "Show that frontier threats can become political powers if left alone.",
    linkedQuest: "Troll Trouble",
    kingdomRole: "First rival polity",
    folder: "Chapter 4 / Troll Trouble",
  }),
  npc("maegar-varn", {
    name: "Maegar Varn",
    role: "Varnhold founder",
    faction: "Varnhold",
    status: "ally",
    disposition: "friendly",
    importance: "major",
    location: "Varnhold",
    agenda: "Build his own frontier settlement and survive the consequences of old discoveries.",
    leverage: "Neighboring authority, personal courage, and information about eastern threats.",
    pressure: "His disappearance turns a friendly neighbor into a kingdom-scale mystery.",
    firstImpression: "Capable, ambitious, and a little too ready to trust bold action.",
    rumor: "Varnhold's silence is alarming because Maegar was not careless.",
    nextScene: "Use his absence as the hook that makes Varnhold feel wrong.",
    linkedQuest: "Save Varnhold",
    kingdomRole: "Neighbor ruler",
    folder: "Chapter 6 / Varnhold",
  }),
  npc("vordakai", {
    name: "Vordakai",
    role: "Ancient cyclops lich",
    faction: "Ancient Cyclops Empire",
    status: "hostile",
    disposition: "hostile",
    importance: "pillar",
    location: "Vordakai's Tomb",
    agenda: "Reclaim power from a dead age and treat modern kingdoms as temporary insects.",
    leverage: "Ancient magic, terror, and a civilization that should have stayed buried.",
    pressure: "His influence shifts the campaign from frontier politics to existential history.",
    firstImpression: "The past opening one eye and finding the present disappointing.",
    rumor: "Some ruins are not empty; they are waiting.",
    nextScene: "Turn every clue in Varnhold into the feeling that the party is late.",
    linkedQuest: "Break Vordakai's Curse",
    kingdomRole: "Ancient existential threat",
    folder: "Chapter 6 / Varnhold",
  }),
  npc("hannis-drelev", {
    name: "Hannis Drelev",
    role: "Baron of Fort Drelev",
    faction: "Fort Drelev",
    status: "rival",
    disposition: "unfriendly",
    importance: "major",
    location: "Fort Drelev",
    agenda: "Preserve his title and comfort even if his subjects pay the price.",
    leverage: "A fortified town, noble title, and political excuses.",
    pressure: "His weakness and compromises can become a regional crisis.",
    firstImpression: "A ruler more afraid of losing status than failing people.",
    rumor: "Fort Drelev's walls protect the baron's pride better than its citizens.",
    nextScene: "Make governance failure personal, not abstract.",
    linkedQuest: "Stabilize Fort Drelev",
    kingdomRole: "Bad-ruler contrast",
    folder: "Chapter 7 / Drelev",
  }),
  npc("castruccio-irovetti", {
    name: "Castruccio Irovetti",
    role: "King of Pitax",
    faction: "Pitax",
    status: "rival",
    disposition: "hostile",
    importance: "pillar",
    location: "Pitax",
    agenda: "Turn art, spectacle, spies, and war into a stage where he looks inevitable.",
    leverage: "Pitax politics, cultural prestige, manipulation, and military reach.",
    pressure: "A rising kingdom near his borders gives him a rival audience to sabotage.",
    firstImpression: "Charming enough to make a threat sound like an invitation.",
    rumor: "Pitax smiles first and pays someone else to draw the knife.",
    secret: "His confidence depends on controlling the story before anyone checks the facts.",
    nextScene: "Use invitations, agents, insults, and public games before open conflict.",
    linkedQuest: "Expose Pitax Intrigue",
    kingdomRole: "Rival monarch",
    folder: "Chapter 8 / Pitax",
  }),
  npc("armag", {
    name: "Armag",
    role: "Tiger Lords war leader",
    faction: "Tiger Lords",
    status: "hostile",
    disposition: "hostile",
    importance: "pillar",
    location: "Glenebon Uplands",
    agenda: "Become the legend his followers need, even if that legend consumes him.",
    leverage: "Warrior charisma, tribal momentum, and old powers tied to the name Armag.",
    pressure: "Each delay gives his legend more room to harden into a kingdom-scale threat.",
    firstImpression: "A man trying to become a myth before the myth devours him.",
    rumor: "Some names are inherited like crowns and curses at once.",
    nextScene: "Distinguish the war leader, the legend, and the force behind both.",
    linkedQuest: "Blood for Blood",
    kingdomRole: "Warrior-legend threat",
    folder: "Chapter 7 / Glenebon",
  }),
  npc("nyrissa", {
    name: "Nyrissa",
    role: "First World manipulator",
    faction: "First World",
    status: "hostile",
    disposition: "hostile",
    importance: "pillar",
    location: "First World",
    agenda: "Shape the Stolen Lands through old pain, fey bargains, and long-game manipulation.",
    leverage: "Fey power, secrecy, emotional wounds, and influence that looks like coincidence.",
    pressure: "Every unresolved fey thread can become part of her larger design.",
    firstImpression: "A beautiful answer to a question the party did not know was dangerous.",
    rumor: "The land has a patron, a predator, or both.",
    secret: "Her role should emerge as a pattern, not a lecture.",
    nextScene: "Seed beauty, grief, or impossible coincidence that later recontextualizes earlier events.",
    linkedQuest: "Face Nyrissa",
    kingdomRole: "Hidden mythic antagonist",
    folder: "Chapter 10 / First World",
  }),
  npc("davik-nettles", {
    name: "Davik Nettles",
    role: "Restless witness",
    faction: "Nettles' Crossing",
    status: "watch",
    disposition: "unfriendly",
    importance: "supporting",
    location: "Nettles' Crossing",
    agenda: "Force the living to answer for the Stag Lord's cruelty.",
    leverage: "Unfinished business and a direct emotional link to the bandit threat.",
    pressure: "He turns the Stag Lord from remote villain into someone with named victims.",
    firstImpression: "Less a quest giver than a wrong that refuses to stay quiet.",
    rumor: "Travelers avoid the crossing even when the detour costs them daylight.",
    nextScene: "Use him when the party needs a personal reason to finish the Stag Lord.",
    linkedQuest: "Confront the Stag Lord",
    folder: "Chapter 3 / Stolen Lands",
  }),
  npc("mikmek", {
    name: "Mikmek",
    role: "Sootscale scout",
    faction: "Sootscale Kobolds",
    status: "watch",
    disposition: "indifferent",
    importance: "supporting",
    location: "Old Sycamore",
    agenda: "Survive faction pressure and get someone stronger to solve a problem the tribe cannot.",
    leverage: "Ground-level truth about the kobold side of the Old Sycamore conflict.",
    pressure: "His fear makes the war feel practical instead of abstract.",
    firstImpression: "Nervous, opportunistic, and more useful than he first appears.",
    rumor: "The mites stole more than property; they stole confidence.",
    nextScene: "Let him point toward kobold politics instead of only a fight.",
    linkedQuest: "Mediate the Old Sycamore War",
    folder: "Chapter 2 / Old Sycamore",
  }),
  npc("tyg-titter-tut", {
    name: "Tyg-Titter-Tut",
    role: "Prankster fey",
    faction: "Local Fey",
    status: "watch",
    disposition: "indifferent",
    importance: "supporting",
    location: "Narlmarches",
    agenda: "Test whether the party can respect the strange rules of the woods.",
    leverage: "Fey perspective, mischief, and clues that arrive sideways.",
    pressure: "Fey incidents can become comic relief or warning signs depending on how the party responds.",
    firstImpression: "Playful enough to underestimate and strange enough to regret underestimating.",
    rumor: "Some laughter in the forest belongs to no visible mouth.",
    nextScene: "Use as a light fey contact who can later make darker fey patterns more believable.",
    linkedQuest: "Map the Greenbelt",
    folder: "Chapter 2 / Fey",
  }),
  npc("melianse", {
    name: "Melianse",
    role: "Nixie local power",
    faction: "Narlmarches Fey",
    status: "watch",
    disposition: "indifferent",
    importance: "supporting",
    location: "Narlmarches",
    agenda: "Protect her water and make mortals recognize that settlement has consequences.",
    leverage: "Control over a local natural feature and the moral weight of habitat conflict.",
    pressure: "She turns resource extraction into a negotiation instead of a map icon.",
    firstImpression: "Beautiful, irritated, and unwilling to be treated as scenery.",
    rumor: "Woodcutters say the water itself has started objecting.",
    nextScene: "Use when a work site, logging plan, or road project needs a living consequence.",
    linkedQuest: "Map the Greenbelt",
    folder: "Chapter 2 / Fey",
  }),
  npc("tiressia", {
    name: "Tiressia",
    role: "Dryad guardian",
    faction: "Narlmarches Fey",
    status: "watch",
    disposition: "friendly",
    importance: "supporting",
    location: "Narlmarches",
    agenda: "Keep her grove alive while deciding if mortal rulers can be trusted.",
    leverage: "Fey knowledge, local goodwill, and a direct tie between nature and kingdom expansion.",
    pressure: "Her trust should be earned through choices, not assumed from good intentions.",
    firstImpression: "Graceful, cautious, and measuring whether promises survive inconvenience.",
    rumor: "Some groves remember every axe raised near them.",
    nextScene: "Offer aid or warning after the party shows how it treats the forest.",
    linkedQuest: "Map the Greenbelt",
    folder: "Chapter 2 / Fey",
  }),
  npc("falchos", {
    name: "Falchos",
    role: "Satyr ally",
    faction: "Narlmarches Fey",
    status: "watch",
    disposition: "friendly",
    importance: "supporting",
    location: "Narlmarches",
    agenda: "Protect Tiressia and keep mortal trouble from hardening into fey vengeance.",
    leverage: "Charm, local paths, and a less formal read on fey mood.",
    pressure: "He can make fey relations feel personal and immediate.",
    firstImpression: "Relaxed until someone threatens the people or places he loves.",
    rumor: "Music in the trees sometimes means welcome and sometimes means warning.",
    nextScene: "Use him to soften a fey scene before revealing the stakes under it.",
    linkedQuest: "Map the Greenbelt",
    folder: "Chapter 2 / Fey",
  }),
  npc("aecora-silverfire", {
    name: "Aecora Silverfire",
    role: "Nomen leader",
    faction: "Nomen Centaurs",
    status: "watch",
    disposition: "indifferent",
    importance: "major",
    location: "Nomen Lands",
    agenda: "Protect her people while deciding whether the party is another outside threat.",
    leverage: "Cultural authority, scouts, and knowledge tied to Varnhold's disappearance.",
    pressure: "The investigation can become diplomacy or war depending on first contact.",
    firstImpression: "Proud, controlled, and unwilling to let outsiders define the truth.",
    rumor: "The plains know which visitors arrive with respect and which arrive with ownership.",
    nextScene: "Make the party ask, listen, and earn information instead of extracting it.",
    linkedQuest: "Save Varnhold",
    kingdomRole: "Regional diplomatic test",
    folder: "Chapter 6 / Nomen",
  }),
  npc("willas-gunderson", {
    name: "Willas Gunderson",
    role: "Varnhold survivor witness",
    faction: "Varnhold",
    status: "watch",
    disposition: "indifferent",
    importance: "supporting",
    location: "Varnhold",
    agenda: "Survive long enough for someone to understand what happened.",
    leverage: "Fragmentary witness details that turn absence into an actionable trail.",
    pressure: "His condition should make Varnhold feel like a disaster, not a puzzle box.",
    firstImpression: "A person carrying too much fear to organize cleanly.",
    rumor: "The missing settlement left behind fewer explanations than footprints.",
    nextScene: "Use him to hand the party one human-scale detail that points toward the larger horror.",
    linkedQuest: "Save Varnhold",
    folder: "Chapter 6 / Varnhold",
  }),
  npc("cephal-lorentus", {
    name: "Cephal Lorentus",
    role: "Varnhold arcane advisor",
    faction: "Varnling Host",
    status: "watch",
    disposition: "indifferent",
    importance: "supporting",
    location: "Varnhold",
    agenda: "Interpret strange evidence through scholarship while carrying his own blind spots.",
    leverage: "Arcane context, records, and a way to make ancient clues less opaque.",
    pressure: "A scholar's confidence can help or mislead depending on what the party verifies.",
    firstImpression: "Educated, strained, and aware that knowledge arrived too late.",
    rumor: "Varnhold had warnings; the problem was knowing which ones mattered.",
    nextScene: "Use him for partial answers, not perfect exposition.",
    linkedQuest: "Break Vordakai's Curse",
    folder: "Chapter 6 / Varnhold",
  }),
  npc("pavetta-stroon-drelev", {
    name: "Pavetta Stroon-Drelev",
    role: "Drelev court power",
    faction: "Drelev Barony",
    status: "rival",
    disposition: "unfriendly",
    importance: "supporting",
    location: "Fort Drelev",
    agenda: "Protect status and influence while the barony's failures close in.",
    leverage: "Court access, family ties, and social pressure inside a failing regime.",
    pressure: "She makes the barony's problems political as well as military.",
    firstImpression: "Polished enough to make cruelty sound like protocol.",
    rumor: "Fort Drelev's court spends more effort assigning blame than solving shortages.",
    nextScene: "Use her when the party needs to see denial dressed as governance.",
    linkedQuest: "Stabilize Fort Drelev",
    folder: "Chapter 7 / Drelev",
  }),
  npc("imeckus-stroon", {
    name: "Imeckus Stroon",
    role: "Drelev court mage",
    faction: "Drelev Barony",
    status: "rival",
    disposition: "unfriendly",
    importance: "supporting",
    location: "Fort Drelev",
    agenda: "Keep power close to the court and make resistance feel impractical.",
    leverage: "Magic, intimidation, and the confidence of someone protected by bad authority.",
    pressure: "His presence turns court failure into a tactical and moral problem.",
    firstImpression: "Precise, cold, and comfortable making fear efficient.",
    rumor: "In Drelev, even rumors watch what they say around the court mage.",
    nextScene: "Use him to make Fort Drelev feel controlled before it feels conquerable.",
    linkedQuest: "Stabilize Fort Drelev",
    folder: "Chapter 7 / Drelev",
  }),
  npc("ilora-nuski", {
    name: "Ilora Nuski",
    role: "Fort Drelev underworld contact",
    faction: "Drelev Shadows",
    status: "watch",
    disposition: "indifferent",
    importance: "supporting",
    location: "Fort Drelev",
    agenda: "Survive the regime, profit from cracks in it, and choose the winning side late.",
    leverage: "Smuggling routes, local secrets, and access that official channels cannot provide.",
    pressure: "Her help should carry a price or future complication.",
    firstImpression: "Practical, guarded, and too experienced to mistake heroes for safety.",
    rumor: "If Fort Drelev has a locked door, someone has already priced the key.",
    nextScene: "Use her when the party needs an unofficial path through a failing settlement.",
    linkedQuest: "Stabilize Fort Drelev",
    folder: "Chapter 7 / Drelev",
  }),
  npc("villamor-koth", {
    name: "Villamor Koth",
    role: "Pitax blade",
    faction: "Pitax",
    status: "rival",
    disposition: "hostile",
    importance: "supporting",
    location: "Pitax",
    agenda: "Make Irovetti's threats credible when charm is no longer enough.",
    leverage: "Violence, reputation, and the ability to turn social conflict physical.",
    pressure: "He reminds the party that Pitax intrigue still has knives behind it.",
    firstImpression: "A professional threat with little interest in moral speeches.",
    rumor: "Some Pitax compliments are delivered by duelists after the party leaves the room.",
    nextScene: "Use him as the hard edge behind Pitax diplomacy.",
    linkedQuest: "Expose Pitax Intrigue",
    folder: "Chapter 8 / Pitax",
  }),
  npc("gasperre-liacenza", {
    name: "Gasperre Liacenza",
    role: "Pitax noble contact",
    faction: "Pitax",
    status: "watch",
    disposition: "indifferent",
    importance: "supporting",
    location: "Pitax",
    agenda: "Read the political wind and decide whether the party is useful, dangerous, or both.",
    leverage: "Social access, court gossip, and a sense for which lies are starting to fail.",
    pressure: "A contact like this can make intrigue actionable without making it simple.",
    firstImpression: "Pleasant, careful, and always counting the audience.",
    rumor: "Pitax's nobles know more than they say and say more than they mean.",
    nextScene: "Use him to trade a clue for a favor, insult, or public commitment.",
    linkedQuest: "Expose Pitax Intrigue",
    folder: "Chapter 8 / Pitax",
  }),
  npc("lantern-king", {
    name: "The Lantern King",
    role: "First World power",
    faction: "Eldest",
    status: "watch",
    disposition: "hostile",
    importance: "pillar",
    location: "First World",
    agenda: "Treat mortal and fey suffering as material for a joke only he fully understands.",
    leverage: "Mythic distance, First World logic, and the ability to make consequence feel like performance.",
    pressure: "His shadow reframes the final arc as more than one antagonist's grievance.",
    firstImpression: "Too amused to be safe and too powerful to dismiss as comic relief.",
    rumor: "Some laughter is not joy; it is ownership.",
    nextScene: "Use sparingly as a final-act pressure behind the visible fey conflict.",
    linkedQuest: "Face Nyrissa",
    kingdomRole: "Mythic final pressure",
    folder: "Chapter 11 / Lantern King",
  }),
]);

export const KINGMAKER_QUEST_LIBRARY = Object.freeze([
  quest("defend-aldori-manor", {
    title: "Defend Aldori Manor",
    status: "watch",
    priority: "Now",
    chapter: "Chapter 1: A Call for Heroes",
    giver: "Jamandi Aldori",
    folder: "Chapter 1 / Opening",
    objective: "Survive the opening attack, protect guests where possible, and prove the party deserves a charter.",
    stakes: "This first crisis defines how Jamandi and survivors judge the party's competence.",
    nextBeat: "Run chaos, triage, witnesses, and hard choices before the road to Oleg's.",
    reward: "Charter credibility, patron trust, and immediate faction context.",
    notes: "Opening-page anchor so the campaign does not skip straight to the trading post.",
  }),
  quest("carry-jamandis-charter", {
    title: "Carry Jamandi's Charter",
    status: "open",
    priority: "Now",
    chapter: "Chapter 1: A Call for Heroes",
    giver: "Jamandi Aldori",
    folder: "Chapter 1 / Opening",
    objective: "Turn a legal charter into visible protection, mapped ground, and useful alliances.",
    stakes: "A charter with no visible results becomes a political liability.",
    linkedEvent: "Jamandi Wants Results",
    nextBeat: "Ask what proof the party can show when Restov next asks what changed.",
    reward: "Political legitimacy and permission to found something lasting.",
  }),
  quest("secure-olegs-trading-post", {
    title: "Secure Oleg's Trading Post",
    status: "open",
    priority: "Now",
    chapter: "Chapter 3: Stolen Lands",
    giver: "Jamandi Aldori",
    folder: "Chapter 3 / Stolen Lands",
    hex: "D4",
    objective: "End the immediate bandit threat and make the trading post a dependable expedition base.",
    stakes: "If Oleg's falls, the charter starts from weakness and local trust collapses.",
    linkedEvent: "First Bandit Collection Run",
    nextBeat: "Let the next bandit move force the party to answer before they feel fully ready.",
    blockers: "Local fear, incomplete knowledge of the bandit network, and limited supplies.",
    reward: "A stable supply hub, credible local allies, and a launch point for hexploration.",
  }),
  quest("break-thorn-river-bandits", {
    title: "Break the Thorn River Bandits",
    status: "watch",
    priority: "Now",
    chapter: "Chapter 3: Stolen Lands",
    giver: "Oleg Leveton",
    folder: "Chapter 3 / Bandits",
    objective: "Find the camp behind the tribute runs and cut the local bandit chain before it reorganizes.",
    stakes: "Leaving the camp intact teaches every other outlaw that the charter can be waited out.",
    linkedEvent: "First Bandit Collection Run",
    nextBeat: "Turn captured bandits, trails, and frightened locals into the next map choice.",
    reward: "Actionable intelligence on the Stag Lord and a safer local road.",
  }),
  quest("recover-svetlanas-ring", {
    title: "Recover Svetlana's Ring",
    status: "watch",
    priority: "Soon",
    chapter: "Chapter 3: Stolen Lands",
    giver: "Svetlana Leveton",
    folder: "Chapter 3 / Stolen Lands",
    hex: "D4",
    objective: "Recover a stolen keepsake and turn a practical bandit problem into a personal promise kept.",
    stakes: "Small harms teach the players what bandit pressure costs ordinary people.",
    nextBeat: "Use the ring as a reminder that victory is not only measured in bodies or coin.",
    reward: "Trust at Oleg's and a human read on the bandit threat.",
  }),
  quest("gather-moon-radishes", {
    title: "Gather Moon Radishes",
    status: "watch",
    priority: "Soon",
    chapter: "Chapter 2: Into the Wild",
    giver: "Svetlana Leveton",
    folder: "Chapter 2 / Into the Wild",
    objective: "Find a local patch of moon radishes and bring back something that feels like normal life returning.",
    stakes: "Morale matters before the kingdom has banners, laws, or walls.",
    nextBeat: "Make this a low-risk exploration favor with charm, tracks, or a small complication.",
    reward: "Hospitality, goodwill, and a simple positive note between harder threats.",
  }),
  quest("help-bokkens-reagents", {
    title: "Help Bokken's Reagent Work",
    status: "watch",
    priority: "Soon",
    chapter: "Chapter 2: Into the Wild",
    giver: "Bokken",
    folder: "Chapter 2 / Into the Wild",
    objective: "Bring Bokken the strange wilderness materials he cannot safely gather alone.",
    stakes: "Useful local experts stay isolated unless the party proves trade is safer than solitude.",
    nextBeat: "Attach the requested reagent to a hex the party already wants to scout.",
    reward: "Potion access, strange warnings, and a useful eccentric contact.",
  }),
  quest("map-greenbelt", {
    title: "Map the Greenbelt",
    status: "open",
    priority: "Soon",
    chapter: "Chapter 2: Into the Wild",
    giver: "Oleg Leveton",
    folder: "Exploration",
    hex: "D4",
    objective: "Explore nearby hexes, identify hazards, and establish reliable routes for future settlement.",
    stakes: "Without map knowledge, every kingdom decision stays reactive.",
    linkedCompanion: "Linzi",
    linkedEvent: "Jamandi Wants Results",
    nextBeat: "Ask the party to choose between safety, speed, and rumor value on the next route.",
    reward: "Routes, discoveries, future region claims, and better encounter prep.",
  }),
  quest("restore-temple-of-elk", {
    title: "Restore the Temple of the Elk",
    status: "watch",
    priority: "Soon",
    chapter: "Chapter 2: Into the Wild",
    giver: "Jhod Kavken",
    folder: "Chapter 2 / Sacred Sites",
    objective: "Find and cleanse a lost sacred place so the Greenbelt feels redeemable, not merely claimable.",
    stakes: "The kingdom needs spiritual trust and restored places, not just military wins.",
    nextBeat: "Let old signs, wildlife behavior, or Jhod's hope point toward the site.",
    reward: "Faith-based support, healing, and a strong public symbol of restoration.",
  }),
  quest("mediate-old-sycamore-war", {
    title: "Mediate the Old Sycamore War",
    status: "watch",
    priority: "Soon",
    chapter: "Chapter 2: Into the Wild",
    giver: "Mikmek",
    folder: "Chapter 2 / Old Sycamore",
    objective: "Understand the mite-kobold conflict and decide whether the party solves it through alliance, force, or both.",
    stakes: "How the party handles small local powers foreshadows how the kingdom will treat nonhuman neighbors.",
    nextBeat: "Give the party a clue that killing everything leaves useful truth buried.",
    reward: "A possible kobold alliance, local stability, and information about nearby threats.",
  }),
  quest("stabilize-sootscale-caverns", {
    title: "Stabilize Sootscale Caverns",
    status: "watch",
    priority: "Soon",
    chapter: "Chapter 2: Into the Wild",
    giver: "Chief Sootscale",
    folder: "Chapter 2 / Old Sycamore",
    objective: "Break Tartuk's hold over the tribe and determine whether the kobolds become enemies or neighbors.",
    stakes: "A peaceful solution gives the future kingdom a better border story than extermination.",
    nextBeat: "Make proof, symbol, or hostage recovery matter before combat decides everything.",
    reward: "Kobold diplomacy, cave access, and a cleaner future claim nearby.",
  }),
  quest("confront-stag-lord", {
    title: "Confront the Stag Lord",
    status: "watch",
    priority: "Now",
    chapter: "Chapter 3: Stolen Lands",
    giver: "Jamandi Aldori",
    folder: "Chapter 3 / Bandits",
    objective: "Find the Stag Lord's fort, break his lieutenants' control, and end the first major threat to the charter.",
    stakes: "The charter cannot become a kingdom while the Stag Lord remains the most feared ruler in the Greenbelt.",
    nextBeat: "Let every bandit clue reveal one more piece of the fort, its people, or its weaknesses.",
    reward: "Political proof, local safety, and the right to move from expedition to founding.",
  }),
  quest("found-first-settlement", {
    title: "Found the First Settlement",
    status: "watch",
    priority: "Soon",
    chapter: "Kingdom Founding",
    giver: "Charter Authority",
    folder: "Kingdom / Founding",
    objective: "Choose a capital site, name the kingdom, assign leadership, and make the first month survivable.",
    stakes: "Founding turns exploration consequences into public policy.",
    linkedEvent: "Jamandi Wants Results",
    nextBeat: "Ask what the first law, first project, and first public promise are.",
    reward: "A capital, kingdom turns, and a reason every map choice has civic consequences.",
  }),
  quest("troll-trouble", {
    title: "Troll Trouble",
    status: "watch",
    priority: "Now",
    chapter: "Chapter 4: Rivers Run Red",
    giver: "Kingdom Council",
    folder: "Chapter 4 / Troll Trouble",
    objective: "Identify why trolls are organizing, protect settlements, and break Hargulka's emerging power.",
    stakes: "An organized monster realm near the border can become a rival polity.",
    nextBeat: "Escalate from isolated attacks to evidence of command, supply, and territorial ambition.",
    reward: "Border security, public confidence, and proof the kingdom can defend itself.",
  }),
  quest("investigate-cult-of-the-bloom", {
    title: "Investigate Cult of the Bloom",
    status: "watch",
    priority: "Now",
    chapter: "Chapter 5: Cult of the Bloom",
    giver: "Kingdom Council",
    folder: "Chapter 5 / Cult of the Bloom",
    objective: "Track Bloom escalation, protect settlements from the outbreak, and identify the force turning local danger into kingdom-scale crisis.",
    stakes: "If the kingdom treats the Bloom as random trouble, the pattern reaches citizens before leaders understand it.",
    nextBeat: "Start with one visible symptom, one frightened witness, and one clue that points past ordinary wilderness danger.",
    reward: "Public confidence, better crisis response, and the campaign's first clear turn toward supernatural pressure.",
  }),
  quest("save-varnhold", {
    title: "Save Varnhold",
    status: "watch",
    priority: "Now",
    chapter: "Chapter 6: The Varnhold Vanishing",
    giver: "Maegar Varn",
    folder: "Chapter 6 / Varnhold",
    objective: "Investigate Varnhold's silence, recover survivors if possible, and learn what power erased a neighbor.",
    stakes: "If a neighboring charter can vanish, the party's kingdom can too.",
    nextBeat: "Begin with absence: meals left cold, posts abandoned, and records that stop too cleanly.",
    reward: "A rescued neighbor, expanded regional knowledge, and the path toward Vordakai.",
  }),
  quest("break-vordakais-curse", {
    title: "Break Vordakai's Curse",
    status: "watch",
    priority: "Now",
    chapter: "Chapter 6: The Varnhold Vanishing",
    giver: "Varnhold Evidence",
    folder: "Chapter 6 / Vordakai",
    objective: "Enter the ancient tomb, defeat the power behind Varnhold's disappearance, and recover what can be saved.",
    stakes: "The campaign shifts from frontier rule to threats older than the kingdom's law.",
    nextBeat: "Make every recovered clue feel like a countdown that already ended once.",
    reward: "Neighbor stability, ancient knowledge, and proof the kingdom can face mythic history.",
  }),
  quest("blood-for-blood", {
    title: "Blood for Blood",
    status: "watch",
    priority: "Now",
    chapter: "Chapter 7: Blood for Blood",
    giver: "Kingdom Council",
    folder: "Chapter 7 / Glenebon",
    objective: "Respond to Tiger Lords pressure, understand Armag's legend, and stop war from defining the kingdom's future.",
    stakes: "A purely military answer may win ground while creating the next generation of enemies.",
    nextBeat: "Present one raid, one diplomatic opening, and one mythic clue pulling in different directions.",
    reward: "Border stability and a more mature military identity.",
  }),
  quest("stabilize-fort-drelev", {
    title: "Stabilize Fort Drelev",
    status: "watch",
    priority: "Now",
    chapter: "Chapter 7: Blood for Blood",
    giver: "Fort Drelev Refugees",
    folder: "Chapter 7 / Drelev",
    objective: "Expose the barony's failures, protect citizens, and decide what lawful intervention looks like.",
    stakes: "The party's kingdom must decide how it treats a neighboring ruler who failed his people.",
    nextBeat: "Use refugees, shortages, and court denial to make the moral problem unavoidable.",
    reward: "Regional trust, new obligations, and a contrast against bad rulership.",
  }),
  quest("expose-pitax-intrigue", {
    title: "Expose Pitax Intrigue",
    status: "watch",
    priority: "Soon",
    chapter: "Chapter 8: War of the River Kings",
    giver: "Kingdom Council",
    folder: "Chapter 8 / Pitax",
    objective: "Trace sabotage, agents, and cultural pressure back to Pitax before the conflict becomes open war.",
    stakes: "Irovetti attacks legitimacy before he attacks walls.",
    nextBeat: "Deliver a problem that looks like local misfortune until one detail points west.",
    reward: "Better diplomatic footing and a chance to set the terms of the conflict.",
  }),
  quest("answer-they-lurk-below", {
    title: "Answer What Lurks Below",
    status: "watch",
    priority: "Now",
    chapter: "Chapter 9: They Lurk Below",
    giver: "Campaign Pressure",
    folder: "Chapter 9 / They Lurk Below",
    objective: "Follow the dread beneath the surface, identify what is rising, and keep fear from becoming a kingdom-wide failure of confidence.",
    stakes: "The kingdom has to prove it can answer threats that do not arrive through roads, courts, or armies.",
    nextBeat: "Use an impossible sign, a missing worker, or an unnerving discovery to pull attention below ground.",
    reward: "A contained deep threat and a sharper bridge into the final First World arc.",
  }),
  quest("face-nyrissa", {
    title: "Face Nyrissa",
    status: "watch",
    priority: "Now",
    chapter: "Chapter 10: Sound of a Thousand Screams",
    giver: "Campaign Pattern",
    folder: "Chapter 10 / First World",
    objective: "Recognize the hidden pattern behind fey pressure and confront the power shaping the Stolen Lands.",
    stakes: "The kingdom cannot endure if its founding story belongs to someone else's wound.",
    nextBeat: "Recontextualize earlier fey scenes as parts of one long design.",
    reward: "Freedom from hidden manipulation and a final answer to what the kingdom means to the land.",
  }),
]);

export const KINGMAKER_LOCATION_LIBRARY = Object.freeze([
  site("aldori-manor", {
    name: "Aldori Manor",
    type: "settlement",
    status: "active",
    controllingFaction: "Restov Swordlords",
    linkedQuest: "Defend Aldori Manor",
    linkedNpc: "Jamandi Aldori",
    folder: "Chapter 1 / Restov",
    whatChanged: "The campaign begins with patronage, tests of competence, and proof that politics can turn violent fast.",
    sceneTexture: "Bright halls, practiced etiquette, sharp steel, and every smile carrying a political edge.",
    opportunities: "Introduce rivals, reveal sponsor expectations, and establish that the charter is a public promise.",
    risks: "Players can treat the opening as ceremony instead of a pressure test.",
    rumor: "Restov already has opinions about which charter parties will survive the first month.",
    notes: "Use as the first proof that social stakes, tactical readiness, and reputation all matter.",
  }),
  site("restov", {
    name: "Restov",
    type: "settlement",
    status: "active",
    hex: "A1",
    controllingFaction: "Restov Swordlords",
    linkedNpc: "Jamandi Aldori",
    folder: "Chapter 1 / Restov",
    whatChanged: "The charter is issued here and later success or failure echoes back into Brevic politics.",
    sceneTexture: "Dueling schools, noble salons, busy roads, and the sound of ambition trying to sound civilized.",
    opportunities: "Patron scenes, political pressure, reinforcements, legal questions, and legitimacy callbacks.",
    risks: "The party's kingdom can be treated as a tool unless it proves an identity of its own.",
    rumor: "Every frontier disaster becomes a city story before the people involved can defend themselves.",
    notes: "Keep Restov as the off-map pressure valve for patronage, scrutiny, and long-term legitimacy.",
  }),
  site("rostland-road", {
    name: "Rostland Road",
    type: "route",
    status: "active",
    controllingFaction: "Restov Swordlords",
    linkedQuest: "Carry Jamandi's Charter",
    folder: "Chapter 1 / Charter Road",
    whatChanged: "The party leaves political safety and starts paying travel costs before reaching the frontier.",
    sceneTexture: "Mud, cold wagon tracks, suspicious travelers, and rumors arriving before facts.",
    opportunities: "Seed early omens, introduce charter rivals, and make supply lines matter.",
    risks: "If skipped entirely, Oleg's Trading Post can feel like a disconnected starting point.",
    rumor: "Caravans have started timing departures around bandit talk instead of weather.",
    notes: "Good place for travel handoffs, random rumor pulls, and first evidence that the Greenbelt is not empty.",
  }),
  site("olegs-trading-post", {
    name: "Oleg's Trading Post",
    type: "settlement",
    status: "threatened",
    hex: "D4",
    controllingFaction: "Oleg's Trading Post",
    linkedQuest: "Secure Oleg's Trading Post",
    linkedEvent: "First Bandit Collection Run",
    linkedNpc: "Oleg Leveton",
    folder: "Chapter 3 / Stolen Lands",
    whatChanged: "The outpost becomes the campaign's first practical base and first test of protection.",
    sceneTexture: "Timber palisade, tired hospitality, guarded stables, and a yard built for trade but braced for violence.",
    opportunities: "Rumor hub, resupply point, early ally scenes, and visible fallout from player decisions.",
    risks: "If the post feels safe too quickly, the bandit threat loses pressure.",
    rumor: "The people here know the difference between law on paper and help arriving in time.",
    notes: "Primary early hub for Greenbelt exploration, bandit pressure, and local trust.",
  }),
  site("bokkens-hut", {
    name: "Bokken's Hut",
    type: "camp",
    status: "active",
    controllingFaction: "Independent",
    linkedQuest: "Help Bokken's Reagent Work",
    linkedNpc: "Bokken",
    folder: "Chapter 2 / Greenbelt",
    whatChanged: "A strange local specialist gives the party a reason to chase useful wilderness errands.",
    sceneTexture: "Herbs, smoke, strange labels, overfull shelves, and a host who is helpful until he is distracting.",
    opportunities: "Alchemy supply, weird rumors, low-stakes errands, and comic relief with practical value.",
    risks: "His scenes can become pure joke unless his information is concretely useful.",
    rumor: "Bokken hears more about roads and injuries than respectable messengers do.",
    notes: "Use as a repeatable support location for supplies, reagents, and odd local tips.",
  }),
  site("thorn-river-camp", {
    name: "Thorn River Camp",
    type: "camp",
    status: "active",
    controllingFaction: "Stag Lord's Bandits",
    linkedQuest: "Break the Thorn River Bandits",
    linkedNpc: "Kressle",
    folder: "Chapter 3 / Bandits",
    whatChanged: "The party can turn a scattered threat into intelligence about the larger bandit structure.",
    sceneTexture: "Hidden trails, rough shelter, stolen goods, and nervous cruelty pretending to be confidence.",
    opportunities: "Capture intel, recover supplies, split bandit loyalties, and point toward the Stag Lord.",
    risks: "A simple fight can hide the larger command chain if no clues survive.",
    rumor: "The river camp is not the top of the bandit ladder, only the nearest rung.",
    notes: "Best early location for showing that banditry is organized, not random.",
  }),
  site("nettles-crossing", {
    name: "Nettles' Crossing",
    type: "landmark",
    status: "rumor",
    controllingFaction: "Haunted Crossing",
    linkedQuest: "Confront the Stag Lord",
    linkedNpc: "Davik Nettles",
    folder: "Chapter 3 / Stolen Lands",
    whatChanged: "A ruined crossing turns bandit violence into a lingering obligation.",
    sceneTexture: "Rotting timbers, cold water, and the sense that old wrongs do not stay buried.",
    opportunities: "Foreshadow the Stag Lord, introduce supernatural consequence, and make justice personal.",
    risks: "If treated only as a ghost encounter, the moral pressure gets lost.",
    rumor: "Travelers avoid the crossing even when it would save time.",
    notes: "Use as a compact reminder that frontier cruelty leaves witnesses.",
  }),
  site("temple-of-the-elk", {
    name: "Temple of the Elk",
    type: "ruin",
    status: "rumor",
    controllingFaction: "Old Faith",
    linkedQuest: "Restore the Temple of the Elk",
    linkedNpc: "Jhod Kavken",
    folder: "Chapter 2 / Sacred Sites",
    whatChanged: "A damaged holy place offers the party a chance to repair the land, not only conquer it.",
    sceneTexture: "Mossed stone, animal signs, sacred silence, and wilderness reclaiming old devotion.",
    opportunities: "Religious ally scenes, healing symbolism, and a non-political source of legitimacy.",
    risks: "The site loses weight if it is reduced to loot and combat.",
    rumor: "Some hunters claim the place watches them back.",
    notes: "Good counterpoint to bandit pressure: the kingdom can heal as well as punish.",
  }),
  site("old-sycamore", {
    name: "Old Sycamore",
    type: "dungeon",
    status: "active",
    controllingFaction: "Mites and Kobolds",
    linkedQuest: "Mediate the Old Sycamore War",
    linkedNpc: "Tartuk",
    folder: "Chapter 2 / Old Sycamore",
    whatChanged: "The party meets a local conflict where choosing sides too quickly can cost future stability.",
    sceneTexture: "Root tunnels, petty war, stolen icons, cramped ambush paths, and old grudges below a landmark tree.",
    opportunities: "Diplomacy, faction play, kobold relations, and a first taste of ruler-style judgment.",
    risks: "If run as only a crawl, the political lesson gets buried.",
    rumor: "The tree marks territory that locals know to avoid after dark.",
    notes: "Use it to teach that the Stolen Lands already have politics before the kingdom arrives.",
  }),
  site("sootscale-caverns", {
    name: "Sootscale Caverns",
    type: "lair",
    status: "active",
    controllingFaction: "Sootscale Kobolds",
    linkedQuest: "Stabilize Sootscale Caverns",
    linkedNpc: "Chief Sootscale",
    folder: "Chapter 2 / Kobolds",
    whatChanged: "A local faction can become an enemy, ally, or cautionary tale depending on how the party handles power.",
    sceneTexture: "Smoke-dark stone, anxious guards, ritual fear, and a leader deciding whether trust is survivable.",
    opportunities: "Alliance, local intelligence, kingdom diplomacy, and consequences for respecting small powers.",
    risks: "Treating kobolds as disposable monsters undermines later ruler themes.",
    rumor: "The tribe is divided between fear, ambition, and exhaustion.",
    notes: "Tie outcomes here to later regional trust and non-human subjects.",
  }),
  site("tuskwater", {
    name: "Tuskwater",
    type: "wilderness",
    status: "active",
    controllingFaction: "Stolen Lands",
    linkedQuest: "Confront the Stag Lord",
    folder: "Chapter 3 / Stolen Lands",
    whatChanged: "The water and nearby terrain frame the final approach to the first major villain.",
    sceneTexture: "Cold shorelines, broken trails, concealed watchers, and the feeling of entering someone else's territory.",
    opportunities: "Approach planning, scouting scenes, and a visual shift from exploration to assault.",
    risks: "Skipping approach pressure makes the Stag Lord's fort feel isolated.",
    rumor: "Bandits know the shoreline paths better than honest travelers do.",
    notes: "Use the area around the Tuskwater to make the first stronghold feel rooted in geography.",
  }),
  site("stag-lords-fort", {
    name: "Stag Lord's Fort",
    type: "lair",
    status: "active",
    controllingFaction: "Stag Lord's Bandits",
    linkedQuest: "Confront the Stag Lord",
    linkedNpc: "The Stag Lord",
    folder: "Chapter 3 / Bandit Stronghold",
    whatChanged: "The first campaign arc resolves by replacing fear-based rule with the party's claim to order.",
    sceneTexture: "Palisades, bad discipline, stolen comforts, and violence held together by reputation.",
    opportunities: "Infiltration, rebellion inside the bandits, final proof of the charter, and a kingdom-founding victory.",
    risks: "A straight frontal assault can miss the internal fractures that make the location memorable.",
    rumor: "The fort is strong because everyone is afraid to test whether the Stag Lord still deserves his name.",
    notes: "Make this the first clear contrast between predatory rule and the party's future rule.",
  }),
  site("narlmarches", {
    name: "Narlmarches",
    type: "wilderness",
    status: "active",
    controllingFaction: "Stolen Lands",
    linkedQuest: "Map the Greenbelt",
    folder: "Regions / Narlmarches",
    whatChanged: "The forest becomes a long-term frontier where resources, fey, monsters, and roads collide.",
    sceneTexture: "Dense canopy, old game trails, hidden clearings, and the sense that the woods decide who is welcome.",
    opportunities: "Resource claims, fey encounters, logging pressure, travel shortcuts, and hidden sanctuaries.",
    risks: "The region can become generic forest if every hex lacks a social or kingdom consequence.",
    rumor: "The trees keep secrets for creatures older than local maps.",
    notes: "Use as the main sandbox region for discovery, fey tone, and early kingdom resource choices.",
  }),
  site("old-beldames-hut", {
    name: "Old Beldame's Hut",
    type: "camp",
    status: "active",
    controllingFaction: "Independent",
    linkedNpc: "Old Beldame",
    folder: "Chapter 2 / Greenbelt",
    whatChanged: "A feared local figure can become a source of medicine, warnings, and social ambiguity.",
    sceneTexture: "Isolated smoke, hanging herbs, sharp hospitality, and neighbors who fear what they do not understand.",
    opportunities: "Local medicine, rumor correction, folk magic tone, and prejudice checks.",
    risks: "Making her only a witch stereotype loses her value as a community mirror.",
    rumor: "People blame the hut for problems they are afraid to understand.",
    notes: "Useful recurring contact for wilderness knowledge and outsider politics.",
  }),
  site("candlemere", {
    name: "Candlemere",
    type: "ruin",
    status: "rumor",
    controllingFaction: "Old Ruins",
    folder: "Chapter 2 / Lake Sites",
    whatChanged: "A mysterious ruin adds ancient danger to what first looked like a bandit-and-frontier problem.",
    sceneTexture: "Mist over water, broken stone, wrong silence, and lights where no safe camp should be.",
    opportunities: "Occult foreshadowing, risky research, and a reason to respect old ruins.",
    risks: "If presented too early as a simple combat stop, the mystery collapses.",
    rumor: "Fisherfolk claim lights move there even when no boat crosses the lake.",
    notes: "Hold this for atmosphere, old magic, and a reminder that maps do not equal understanding.",
  }),
  site("tatzlford", {
    name: "Tatzlford",
    type: "settlement",
    status: "active",
    controllingFaction: "Frontier Settlers",
    folder: "Chapter 4 / Settlements",
    whatChanged: "A frontier settlement turns exploration wins into governance obligations.",
    sceneTexture: "Fresh-cut timber, unfinished defenses, hopeful families, and a road that still feels provisional.",
    opportunities: "Settlement projects, citizen requests, local leaders, and proof the kingdom is becoming real.",
    risks: "Ignoring its needs makes the kingdom feel like a spreadsheet instead of a community.",
    rumor: "People here measure rulers by repairs finished, not speeches made.",
    notes: "Use as an early model for settlement care, roads, and visible kingdom growth.",
  }),
  site("hargulkas-stronghold", {
    name: "Hargulka's Stronghold",
    type: "lair",
    status: "active",
    controllingFaction: "Troll Kingdom",
    linkedQuest: "Troll Trouble",
    linkedNpc: "Hargulka",
    folder: "Chapter 4 / Troll Trouble",
    whatChanged: "The troll threat reveals that monsters can organize like a rival kingdom.",
    sceneTexture: "Heavy stone, smoke, war trophies, and brute order trying to become politics.",
    opportunities: "Military response, intelligence gathering, border defense, and a test of the kingdom's protection promise.",
    risks: "Running it as random monster cleanup weakens the rival-state theme.",
    rumor: "The trolls are no longer behaving like scattered predators.",
    notes: "Frame as a border crisis and ideological contrast, not just a dungeon.",
  }),
  site("cradle-of-lamashtu", {
    name: "The Cradle of Lamashtu",
    type: "dungeon",
    status: "rumor",
    controllingFaction: "Cult of the Bloom",
    linkedQuest: "Investigate Cult of the Bloom",
    folder: "Chapter 5 / Cult of the Bloom",
    whatChanged: "The Bloom crisis points to a source instead of remaining a string of unrelated incidents.",
    sceneTexture: "Sickness, unnatural growth, frightened reports, and sacred wrongness closing around a concrete lead.",
    opportunities: "Crisis triage, investigation, settlement protection, and a tonal shift from frontier problem to supernatural campaign pressure.",
    risks: "If the Bloom arrives without a visible trail, the chapter can feel like a sudden random outbreak.",
    rumor: "People describe the same wrongness in different places before they agree on what it means.",
    notes: "Use as the chapter-five anchor card without copying adventure text.",
  }),
  site("varnhold", {
    name: "Varnhold",
    type: "settlement",
    status: "unstable",
    controllingFaction: "Varnling Host",
    linkedQuest: "Save Varnhold",
    linkedNpc: "Maegar Varn",
    folder: "Chapter 6 / Varnhold",
    whatChanged: "A neighboring charter settlement going silent turns kingdom play into regional mystery.",
    sceneTexture: "Abandoned routines, half-finished chores, empty streets, and the horror of absence.",
    opportunities: "Investigation, diplomacy with neighbors, recovered records, and fear for the party's own kingdom.",
    risks: "If clues are too sparse, players may not know what action is possible.",
    rumor: "No one agrees on when the silence started, only that it feels wrong.",
    notes: "Use absence as the encounter: what is missing matters as much as what remains.",
  }),
  site("nomen-lands", {
    name: "Nomen Lands",
    type: "wilderness",
    status: "active",
    controllingFaction: "Nomen Centaurs",
    linkedQuest: "Save Varnhold",
    linkedNpc: "Aecora Silverfire",
    folder: "Chapter 6 / Nomen Heights",
    whatChanged: "The party must solve regional truth without treating local peoples as obstacles.",
    sceneTexture: "Open sky, grassland tracks, wary scouts, and diplomacy where every assumption is noticed.",
    opportunities: "Cultural respect, alliance, war avoidance, and deeper context for Varnhold.",
    risks: "A careless approach can turn an investigation into avoidable conflict.",
    rumor: "The plains remember who rides with respect and who rides like an owner.",
    notes: "Make this a diplomatic and investigative region, not just travel between clues.",
  }),
  site("vordakais-tomb", {
    name: "Vordakai's Tomb",
    type: "dungeon",
    status: "active",
    controllingFaction: "Ancient Cyclops Power",
    linkedQuest: "Break Vordakai's Curse",
    linkedNpc: "Vordakai",
    folder: "Chapter 6 / Vordakai",
    whatChanged: "The campaign reveals that ancient powers can erase modern settlements without negotiating.",
    sceneTexture: "Cyclopean stone, stale air, old hunger, and evidence that history can still act.",
    opportunities: "High-stakes dungeon play, lore reveals, rescued consequences, and a mythic escalation.",
    risks: "If the tomb is only a crawl, the tragedy of Varnhold becomes background.",
    rumor: "Some ruins are not dead; they are waiting to be remembered incorrectly.",
    notes: "Use it as the pivot from frontier politics to ancient existential threat.",
  }),
  site("dunsward", {
    name: "Dunsward",
    type: "wilderness",
    status: "active",
    controllingFaction: "Tribal and Frontier Powers",
    linkedQuest: "Blood for Blood",
    folder: "Chapter 7 / Glenebon",
    whatChanged: "The frontier widens into raiding pressure, old legends, and contested identity.",
    sceneTexture: "Broad grass, war trails, smoke on horizons, and songs that carry farther than maps.",
    opportunities: "Diplomacy, military response, legend research, and hard calls about force.",
    risks: "Reducing the region to combat loses the culture-and-legend pressure.",
    rumor: "Some riders are following a war leader; others are following an old story.",
    notes: "Keep every fight tied to a reason, rumor, or political consequence.",
  }),
  site("fort-drelev", {
    name: "Fort Drelev",
    type: "settlement",
    status: "unstable",
    controllingFaction: "Drelev Barony",
    linkedQuest: "Stabilize Fort Drelev",
    linkedNpc: "Hannis Drelev",
    folder: "Chapter 7 / Drelev",
    whatChanged: "A failed neighboring ruler becomes a mirror for what the party's kingdom must not become.",
    sceneTexture: "Fortified fear, thin stores, guarded speech, and people who know authority can abandon them.",
    opportunities: "Refugee aid, political intervention, covert work, and moral contrast.",
    risks: "If presented as only enemy territory, the civilian stakes disappear.",
    rumor: "People speak in practical needs because hope has become dangerous.",
    notes: "Use Fort Drelev to test what lawful rescue looks like when another ruler failed.",
  }),
  site("hooktongue-slough", {
    name: "Hooktongue Slough",
    type: "wilderness",
    status: "active",
    controllingFaction: "Local Predators and Smugglers",
    linkedQuest: "Stabilize Fort Drelev",
    folder: "Chapter 7 / Drelev",
    whatChanged: "Wetlands complicate movement, supply, and rescue while hiding both threats and routes.",
    sceneTexture: "Black water, biting insects, half-sunk tracks, and voices carrying through fog.",
    opportunities: "Stealth routes, survival pressure, hidden allies, and supply-line scenes.",
    risks: "Navigation can feel like filler unless each delay changes the stakes.",
    rumor: "The swamp knows more about Fort Drelev than its walls admit.",
    notes: "Use as hostile terrain that creates choices instead of just slowing travel.",
  }),
  site("glenebon-uplands", {
    name: "Glenebon Uplands",
    type: "wilderness",
    status: "active",
    controllingFaction: "Tiger Lords Pressure",
    linkedQuest: "Blood for Blood",
    linkedNpc: "Armag",
    folder: "Chapter 7 / Glenebon",
    whatChanged: "Legend, warfare, and succession pressure collide on the kingdom's frontier.",
    sceneTexture: "Wind over high ground, war camps, old cairns, and pride sharpened into a blade.",
    opportunities: "Military scouting, mythic clues, diplomacy, and tests of restraint.",
    risks: "Treating every camp as identical makes Armag's story feel generic.",
    rumor: "The land has started producing the kind of story people follow into war.",
    notes: "Keep the region tied to identity: who gets to define strength, rulership, and legacy.",
  }),
  site("pitax", {
    name: "Pitax",
    type: "settlement",
    status: "active",
    controllingFaction: "Pitax",
    linkedQuest: "Expose Pitax Intrigue",
    linkedNpc: "Castruccio Irovetti",
    folder: "Chapter 8 / Pitax",
    whatChanged: "The campaign shifts from frontier survival to legitimacy warfare with art, agents, and sabotage.",
    sceneTexture: "Perfume, applause, sharp gossip, crowded salons, and threats hidden behind culture.",
    opportunities: "Spy play, diplomacy, propaganda, social duels, and public counter-narratives.",
    risks: "If Pitax becomes only an army target, Irovetti's cultural weapon disappears.",
    rumor: "In Pitax, an insult can travel faster than a scout.",
    notes: "Use it as a war of reputation before it becomes a war of forces.",
  }),
  site("rushlight-tournament", {
    name: "Rushlight Tournament Grounds",
    type: "landmark",
    status: "active",
    controllingFaction: "Pitax",
    linkedQuest: "Expose Pitax Intrigue",
    linkedNpc: "Castruccio Irovetti",
    folder: "Chapter 8 / Pitax",
    whatChanged: "A public contest becomes a stage for alliances, insults, and political trap-setting.",
    sceneTexture: "Bright banners, watched smiles, rigged hospitality, and spectators hungry for stories.",
    opportunities: "Social victories, rival introductions, public proof of competence, and planted clues.",
    risks: "Running events as disconnected mini-games loses the intrigue spine.",
    rumor: "Everyone arrives to compete; not everyone arrives to win fairly.",
    notes: "Make every contest change a relationship, rumor, or diplomatic position.",
  }),
  site("whiterose-abbey", {
    name: "Whiterose Abbey",
    type: "ruin",
    status: "rumor",
    controllingFaction: "Old Secrets",
    linkedQuest: "Expose Pitax Intrigue",
    folder: "Chapter 8 / Pitax",
    whatChanged: "An old site gives Pitax-era investigation a darker, older texture.",
    sceneTexture: "Cold stone, overgrown paths, old devotion turned secretive, and silence with too much structure.",
    opportunities: "Clues, old crimes, hidden agents, and a break from courtly pressure.",
    risks: "Without links back to Pitax, the location can feel like a side dungeon.",
    rumor: "Some places survive by making everyone agree not to ask what happened there.",
    notes: "Use to connect intrigue, old history, and physical investigation.",
  }),
  site("depth-of-fear", {
    name: "The Depth of Fear",
    type: "dungeon",
    status: "rumor",
    controllingFaction: "They Lurk Below",
    linkedQuest: "Answer What Lurks Below",
    folder: "Chapter 9 / They Lurk Below",
    whatChanged: "The campaign turns a buried threat into an active pressure on the kingdom's safety and confidence.",
    sceneTexture: "Claustrophobic paths, quiet panic, signs of something moving below, and citizens realizing the ground is not neutral.",
    opportunities: "Horror pacing, underground exploration, public reassurance, and a clean escalation between Pitax and the First World finale.",
    risks: "If handled as an isolated dungeon, the chapter can feel disconnected from the kingdom it threatens.",
    rumor: "The first warnings sound too strange for court reports until someone fails to come back.",
    notes: "Use as the chapter-nine anchor card without importing adventure prose.",
  }),
  site("castle-of-knives", {
    name: "Castle of Knives",
    type: "landmark",
    status: "rumor",
    controllingFaction: "First World Influence",
    linkedQuest: "Face Nyrissa",
    linkedNpc: "Nyrissa",
    folder: "Chapter 10 / First World",
    whatChanged: "The hidden fey pattern becomes visible enough to track toward the campaign's final truth.",
    sceneTexture: "Impossible edges, wrong reflections, thorned beauty, and spaces that remember pain.",
    opportunities: "Fey revelations, old bargains, symbolic encounters, and final-act foreshadowing.",
    risks: "If the First World is only random weirdness, Nyrissa loses narrative clarity.",
    rumor: "Travelers describe the place differently, but all agree it felt personal.",
    notes: "Use as a threshold where symbolism starts functioning like geography.",
  }),
  site("house-at-the-edge-of-time", {
    name: "House at the Edge of Time",
    type: "dungeon",
    status: "rumor",
    controllingFaction: "Nyrissa",
    linkedQuest: "Face Nyrissa",
    linkedNpc: "Nyrissa",
    folder: "Chapter 10 / First World",
    whatChanged: "The campaign moves from kingdom defense to confronting the source of the pattern.",
    sceneTexture: "Rooms out of sequence, grief preserved as architecture, beauty with teeth, and memories that refuse to stay past.",
    opportunities: "Final revelations, companion callbacks, hard moral choices, and the hidden logic behind prior fey pressure.",
    risks: "If not tied to earlier choices, it can feel detached from the kingdom story.",
    rumor: "The house is not found by roads; it is found by consequences.",
    notes: "Anchor final-act scenes to promises, losses, and themes the party created over the campaign.",
  }),
  site("thousandbreaths", {
    name: "Thousandbreaths",
    type: "wilderness",
    status: "rumor",
    controllingFaction: "First World",
    linkedQuest: "Face Nyrissa",
    linkedNpc: "Nyrissa",
    folder: "Chapter 10 / First World",
    whatChanged: "The fey layer behind the Stolen Lands becomes active terrain instead of background mystery.",
    sceneTexture: "Breathing forest, shifting paths, impossible seasons, and emotion changing the weather.",
    opportunities: "Fey travel, dream logic, symbolic skill scenes, and direct pressure on kingdom identity.",
    risks: "Too much abstraction can leave players unsure what choices matter.",
    rumor: "Some paths enter the forest as roads and leave as memories.",
    notes: "Use clear goals inside surreal framing so the players can act decisively.",
  }),
]);
